# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [94]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

### What does it mean when you provide fewer indices than axes when slicing? See example below.

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
#import numpy as np

#MATRIX_1 = np.array([[1, 2, 3],
#                     [4, 5, 6]])

#MATRIX_2 = np.array([[9, 8, 7],
#                     [6, 5, 4]])
##Result
#MATRIX_R = np.array([[0, 0, 0],
#                     [0, 0, 0]])

#r = row, all rows begin with 0
#c = column, all columns begin with 0
#def add_mult_matrices(a, b, *, val):
#    global MATRIX_R
#    if val == 'Add' and MATRIX_1.shape == MATRIX_2.shape:
#        for r in range(2):
#            for c in range(3):
#                MATRIX_R[r][c] = MATRIX_1[r][c] + MATRIX_2[r][c]
#    elif val == 'Mult' and MATRIX_1.shape[1] == MATRIX_2.shape[0]:
#        for r in range(2):
#            for c in range(3):
#                MATRIX_R[r][c] = MATRIX_1[r][c] * MATRIX_2[r][c]
#    elif val == 'Add' and MATRIX_1.shape != MATRIX_2.shape:
#        MATRIX_R = "Wrong shape"
#    elif val == 'Mult' and MATRIX_1.shape[1] != MATRIX_2.shape[0]:
#        MATRIX_R = "Not defined, mult calc not possible"
#    elif (val == 'Add' or val == 'Mult') and (isinstance(a,np.ndarray) == 0 or isinstance(b,np.ndarray) == 0):
#        MATRIX_R = "Not type numpy.ndarray"
#    else: MATRIX_R = "Add or Mult"
    
#add_mult_matrices(MATRIX_1, MATRIX_2, val ='Add')
#print(MATRIX_R)
    

[[10 10 10]
 [10 10 10]]


In [108]:
import numpy as np

MATRIX_1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

MATRIX_2 = np.array([[9, 8, 7],
                     [6, 5, 4]])

def add_mult_matrices(a, b, *, val):
    if val == 'Add' and MATRIX_1.shape == MATRIX_2.shape:
        result = MATRIX_1 + MATRIX_2
    elif val == 'Mult' and MATRIX_1.shape[1] == MATRIX_2.shape[0]:
        result = MATRIX_1 @ MATRIX_2
    elif val == 'Add' and MATRIX_1.shape != MATRIX_2.shape:
        result = "Wrong shape"
    elif val == 'Mult' and MATRIX_1.shape[1] != MATRIX_2.shape[0]:
        result = "Not defined, mult calc not possible"
    elif (val == 'Add' or val == 'Mult') and (isinstance(a,np.ndarray) == 0 or isinstance(b,np.ndarray) == 0):
        result = "Not type numpy.ndarray"
    else: result = "Add or Mult"
    print(result)
add_mult_matrices(MATRIX_1, MATRIX_2, val ='Add')

[[10 10 10]
 [10 10 10]]


In [ ]:
import numpy as np
# enligtläraren
def add_mult_matrices(arr1, arr2, operator):
    isArray = isinstance(arr1, np.ndarray) and isinstance(arr2, np.ndarray)
    isOperator = operator == "add" or operator == "mult"
    
    if isArray and isOperator:
        if operator == "add":
            if np.shape(arr1) == np.shape(arr2):
                return arr1 + arr2
            else:
                print("Matrix addition: Two matrices needs to have same dimensions")
        elif operator == "mult":
            if arr1.shape[1] == arr2.shape[0]:
                return arr1 @ arr2
            else:
                print("Matrix mult, first matrix needs to have as many columns as the second matrix have rows")
    else:
        print("Needs two numpy arrays and add or mult as argument")
        
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[9, 8, 7],[6, 5, 4]])

add_mult_matrices(arr1, arr2, "add")

Needs two numpy arrays and add or mult as argument


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?