# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [25]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [49]:
A = np.arange(1, 16).reshape(3,5)
print("Dimension:",A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Type:", type(A))

Dimension: 2
Shape: (3, 5)
Size: 15
Type: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [52]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

# Subtraction matrices
X = np.subtract(B, C)
print("Result B-C:\n", X)

# Multiplication matrices
D = B @ C
print("Result B @ C:\n", D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Result B-C:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Result B @ C:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [53]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

#exponentiate
exp_array = np.exp (D)
print("Exponentiate:\n",exp_array)

#min value in matrix
min_value_matrix = np.min(D)
print("Min value matrix:\n", min_value_matrix)

#min value in each row
min_value_row = np.min(D, axis=1)
print("Min value each row:\n", min_value_row)

#min value in each column
min_value_column = np.min(D, axis=0)
print("Min value each column:\n", min_value_column)

#index value min value in matrix
min_value_index = np.argmin(D)
print("Min value index in matrix:\n", min_value_index)

#min value index in each row
min_value_index_row = np.argmin(D, axis=1)
print("Min value index each row:\n", min_value_index_row)

#sum all elements
sum_result = np.sum(D)
print("Sum all elements:\n", sum_result)

#mean for each column
mean_column = np.mean(D, axis=0)
print("Mean each columns:\n", mean_column)

#median for each column
median_column = np.median(D, axis=0)
print("Median each columns:\n", median_column)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Exponentiate:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Min value matrix:
 1
Min value each row:
 [1 4 7]
Min value each column:
 [1 2 3]
Min value index in matrix:
 0
Min value index each row:
 [0 0 0]
Sum all elements:
 45
Mean each columns:
 [4. 5. 6.]
Median each columns:
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [54]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [55]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
#We get all columns for that row index. In this example, for row 1 we get values from all three columns [1,0], [1,1] and [1,2]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [56]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [58]:
#answer
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1)) 
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Answer. Will reshape the 1-D array to a 3-D array. Two columns and three rows. -1 lets numpy solve the splitting of values per row. 
# We could have replaced the -1 with value 5 in this case. We know there are 30 elements so 2*3*5=30. That would have given us the same
# result.

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [83]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [79]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [39]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [87]:
import numpy as np
import numpy.ma as ma

matrix_1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_2 = np.array([[9, 8, 7],
                     [6, 5, 4]])


#check for valid matrix by comparing no of columns in matrix_1 with no of rows in matrix_2. 
cols = matrix_1.shape[1]
rows = matrix_2.shape[0]

#chack for valid matrix for adding operation. Shape must be equal
matrix_1_shape = ma.shape(matrix_1)
matrix_2_shape = ma.shape(matrix_2)

# input. Add or Mult is valid

#check if valid and give output
def add_mult_matrices(a, b, *, val):
    if val == 'Add' and matrix_1_shape != matrix_2_shape:
        vval = val
        result = "Wrong shape"
        print("Input:", val, "\n", result)
    elif val == 'Mult' and rows != cols:
        vval = val
        result = "Not defined, mult calc not possible"
        print("Input:", val, "\n", result)
    elif (val == 'Add' or val == 'Mult') and (isinstance(a,np.ndarray) == 0 or isinstance(b,np.ndarray) == 0):
        vval = val
        result = "Not type numpy.ndarray:"
        print("Input:", val, "\n", result)
    elif val == 'Add' and matrix_1_shape == matrix_2_shape:
        vval = val 
        result = a + b
        print("Input:", val, "\n", result)
    elif val == 'Mult' and rows == cols:
        vval = val
        result = a @ b
        print(val, "\n", result)
    else: print("Wrong input. Use Add or Mult")
          
add_mult_matrices(matrix_1, matrix_2, val ='Add')

#print controll values

print("\nControll values:")
print("If #columns in matrix_1 <> # rows in matrix_2. Multiplication not possible: Not defined")
print(" No of columns in matrix_1 =", cols, "and no of rows in matrix_2 =", rows, "True/False:", cols == rows)
print("If matrix_1 and materix_2 does not have same shape, adding function is not possible:")
print(" Shape matrix_1:", matrix_1_shape, "and shape matrix_2:", matrix_2_shape, "True/False:", matrix_1_shape == matrix_2_shape)
print("Both matrix must have type ndarray:")
print(" Matrix_1:", isinstance(matrix_1,np.ndarray))
print(" Matrix_2:", isinstance(matrix_2,np.ndarray))



Input: Add 
 [[10 10 10]
 [10 10 10]]

Controll values:
If #columns in matrix_1 <> # rows in matrix_2. Multiplication not possible: Not defined
 No of columns in matrix_1 = 3 and no of rows in matrix_2 = 2 True/False: False
If matrix_1 and materix_2 does not have same shape, adding function is not possible:
 Shape matrix_1: (2, 3) and shape matrix_2: (2, 3) True/False: True
Both matrix must have type ndarray:
 Matrix_1: True
 Matrix_2: True


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [88]:
#10.1.1
x = np.array([[4, 3]])
#a dimensions
print("a:", x.shape)

#b 5x
result = np.multiply(x, 5)
print("b:", result)

#c 3x
result = np.multiply(x, 3)
print("c:", result)

#d 5x+3x
result = np.multiply(x, 5) + np.multiply(x, 3)
print("d:", result)

#e 8x
result = np.multiply(x, 8)
print("e:", result)

#f 4x-x
result = np.multiply(x, 4) - np.multiply(x, 1)
print("f:", result)

#g ny dim efter transponering
xt = x.transpose()
print("g:", xt)
print("g, new shape:", xt.shape)

#h definierat?
b = x.shape == xt.shape
print("h, Ej definierat, shape x <> shape xt:", b)

#i beräkna (normen) ||x||
norm = np.linalg.norm(x)
print("i: Norm:", norm)



a: (1, 2)
b: [[20 15]]
c: [[12  9]]
d: [[32 24]]
e: [[32 24]]
f: [[12  9]]
g: [[4]
 [3]]
g, new shape: (2, 1)
h, Ej definierat, shape x <> shape xt: False
i: Norm: 5.0


In [89]:
#10.1.2
v = np.array([[3],
              [7],
              [0],
              [11]])
#a
print("a: dimension", v.shape)

#b 2v
result = np.multiply(v, 2)
print("b:", result)

#c 5v+2v
result = np.multiply(v, 5) + np.multiply(v, 2)
print("c:", result)

#d 4v-2v
result = np.multiply(v, 4) - np.multiply(v, 2)
print("d:", result)

#e vT new dimensions
vt = v.transpose()
print("e:", vt)
print("e, new shape:", vt.shape)

#f norm ||v||
norm = np.linalg.norm(v)
print("f: Norm:", norm)

a: dimension (4, 1)
b: [[ 6]
 [14]
 [ 0]
 [22]]
c: [[21]
 [49]
 [ 0]
 [77]]
d: [[ 6]
 [14]
 [ 0]
 [22]]
e: [[ 3  7  0 11]]
e, new shape: (1, 4)
f: Norm: 13.379088160259652


In [90]:
#10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

#a beräkna norm ||v1||
norm = np.linalg.norm(v1)
print("a: Norm:", norm)

#b beräkna norm ||v1-v2||
norm = np.linalg.norm(v1-v2) 
print("b:", norm)

a: Norm: 7.14142842854285
b: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [91]:
#10.2.1 

A = np.array([[2, 1, -1],
                [1, -1, 1]])
B = np.array([[4, -2, 1],
                [2, -4, -2]])
C = np.array([[1, 2],
                [2, 1]])
D = np.array([[3, 4],
                [4, 3]])
E = np.array([[1],
                [2]])
I = np.array([[1, 0],
                [0, 1]])
#a check if definierat för 2A, om ja, utför beräkning. Är mult med sig själv

result = np.multiply(A, 2)
print("a:", result)

#b B-2A

result = B - np.multiply(A, 2)
print("Definierad:", B.shape == A.shape, "\nb:", result)


#c 3C-2E
b = C.shape == E.shape

if b == 0:
    result = ("c: Not defined")
    print(result)
else: 
    result = np.multiply(C, 3) - np.multiply(E, 2)
    print("c:", result)

#d 2D-3C
d = D.shape == C.shape

if d == 0:
    result = ("d: Not defined")
    print(result)
else: 
    result = np.multiply(D, 2) - np.multiply(C, 3)
    print("d:", result)
    
#e DT + 2D
dt = D.transpose()
e = dt.shape == D.shape

if e == 0:
    result = ("e: Not defined")
    print(result)
else: 
    result = np.multiply(dt, 1) + np.multiply(D, 2)
    print("e:", result)

#f 2CT - 2DT

ct = C.transpose()
dt = D.transpose()
f = ct.shape == dt.shape

if f == 0:
    result = ("f: Not defined")
    print(result)
else: 
    result = np.multiply(ct, 2) - np.multiply(dt, 2)
    print("f:", result)

#g AT - B
at = A.transpose()
g = at.shape == B.shape

if g == 0:
    result = ("g: Not defined")
    print(result)
else: 
    result = np.multiply(at, 1) - np.multiply(B, 1)
    print("g:", result)
    
#h AC

cols = A.shape[1]
rows = C.shape[0]

if rows != cols:
    result = "h: Not defined"
    print(result)
else:
    result = A @ C
    print("h:", result)
    
#i CD

cols = C.shape[1]
rows = D.shape[0]

if rows != cols:
    result = "i: Not defined"
    print(result)
else:
    result = C @ D
    print("i:", result)

#j CB

cols = C.shape[1]
rows = B.shape[0]

if rows != cols:
    result = "j: Not defined"
    print(result)
else:
    result = C @ B
    print("j:", result)
    
#k CI

cols = C.shape[1]
rows = I.shape[0]

if rows != cols:
    result = "k: Not defined"
    print(result)
else:
    result = C @ I
    print("k:", result)
    
#l ABT
bt = B.transpose()
cols = A.shape[1]
rows = bt.shape[0]

if rows != cols:
    result = "l: Not defined"
    print(result)
else:
    result = A @ bt
    print("l:", result)

a: [[ 4  2 -2]
 [ 2 -2  2]]
Definierad: True 
b: [[ 0 -4  3]
 [ 0 -2 -4]]
c: Not defined
d: [[3 2]
 [2 3]]
e: [[ 9 12]
 [12  9]]
f: [[-4 -4]
 [-4 -4]]
g: Not defined
h: Not defined
i: [[11 10]
 [10 11]]
j: [[  8 -10  -3]
 [ 10  -8   0]]
k: [[1 2]
 [2 1]]
l: [[5 2]
 [7 4]]


In [93]:
#10.2.2 definiera matrisen

A = np.array([[2, 3, 4],
              [5, 4, 1]])

at = A.transpose()
cols = A.shape[1]
rows = at.shape[0]

if rows != cols:
    result = "Not defined"
    print(result)
else:
    result = A @ at
    print(result)

[[29 26]
 [26 42]]


In [94]:
#10.2.3

A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

AB = A @ B
print("AB:", AB)
AC = A @ C
print("AC:", AC)
print("B:", B)
print("C:", C)
print("AB = AC men B<>C")
              

AB: [[ 4  7]
 [ 8 14]]
AC: [[ 4  7]
 [ 8 14]]
B: [[2 1]
 [1 3]]
C: [[4 3]
 [0 2]]
AB = AC men B<>C


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [95]:
v1 = np.arange(4)
v2 = v1[-2:123]
print("v1:", v1)
print("v2:", v2)
#v1.base is None # check if copy
#v2.base #get a view
print("v1.base: ", v1.base)
print("v2.base: ", v2.base)
print("v1 is the original array (even if the .base gives value None = copy) and will not be affected by changes in a view. A view is only a view of the original array")

v1: [0 1 2 3]
v2: [2 3]
v1.base:  None
v2.base:  [0 1 2 3]
v1 is the original array (even if the .base gives value None = copy) and will not be affected by changes in a view. A view is only a view of the original array
